- hosts: "*"
  become: yes
# Backup Volumes from Docker
  tasks:
    - name: Make the volumes backup
      archive:
        path: /var/lib/docker/volumes
        dest: /var/NFS/Docker_Repo/volumes/Volumes_{{ansible_date_time.date}}.tar.gz

  tasks:
    - name: find all files that are older than 15 days
      find:
        paths: /var/NFS/Docker_Repo/volumes/
        age: 15d
        recurse: yes
      register: filesOlderThan15
    - name: remove older than 15 days
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ filesOlderThan15.files }}"
